### ISSUE TITLE
/usr/lib/libstdc++.so.6: no version information available

### ISSUE THREAD

**Issue by kreatoo** [gkisslinux/grepo#18]
Hello, i started using gkiss
But when i run some apps i get this error and app wont run:
/usr/lib/libstdc++.so.6: no version information available
I tried firefox (the tarball on the official website) and tried qutebrowser that i installed thru pip, and both gave the same error. This does not occur on my other gentoo installation.
How can i fix this?

**Comment by git-bruh** [comment]
I'm not really sure why this happens, but it seems to be related to different versions of the toolchain used to build the binary and the toolchain on the target system. Ideally binaries that are created with the aim of distribution would be built with '-static-libgcc -static-libstdc++' but that's not the case. I had this issue once so as a workaround you can just grab the libstdc++.so.6 from gentoo/arch/whatever, put it in a local path and LD_PRELOAD it before running the binary. Also, would these binaries run anyways considering that they're probably linked to dbus/pulseaudio and also xorg ? I'll look into it. Does it hard error out after the stdc++ error or are there more ?

**Comment by kreatoo** [comment]
it does hard error out stdc. I tried using Arch's libstdc++, but it ended up with a different error.

**Comment by kreatoo** [comment]
Now firefox works, but qutebrowser sadly doesnt.

**Comment by kreatoo** [comment]
I decided to leave gkiss for gentoo, thanks for your time
