### ISSUE TITLE
glibc fails to build (static declaration issue)

### ISSUE THREAD

**Issue by davidgarland** [gkisslinux/grepo#19]
While building glibc going through the fresh install process for GKISS, I am getting the following error (abusing discord as a CDN here, additionally sorry for screenshot of text but I am not even into GUI yet):

https://media.discordapp.net/attachments/313639629146423296/885299296369532928/20210908_180114.jpg

Any workaround? I've made sure I am using GNU Awk and GNU Grep, so I don't know what it could be if it is indeed user error.

**Comment by git-bruh** [comment]
This seems to be caused by bison 3.8. You can temporarily 'kiss fork bison; cd bison; sed -i 's/3.8/3.7.6/g' version; kiss c; kiss b' and rebuild glibc with the old bison, and upgrade it again. I'll look for a proper fix.
