### ISSUE TITLE
firefox depends on libepoxy; libepoxy not found

### ISSUE THREAD

**Issue by davidgarland** [gkisslinux/grepo#21]
I have:
```
grepo/bin
grepo/core
grepo/extra
grepo/wayland
community/community
grepo/repo/core
grepo/repo/extra
grepo/repo/wayland
kiss-xorg/xorg
```
libepoxy is not available in any of these, but grepo/bin/firefox depends on libepoxy. is there a recommended place to get it?

**Comment by git-bruh** [comment]
Sorry i had forgotten to update the dependencies of the bin package, it doesn't need libepoxy. Also you don't need ot add grepo/kiss-repo/* to your KISS_PATH since grepo/* already contain symlinks to it (Not sure if you meant to show the directory tree or all the repos you added to the kiss path).

**Comment by davidgarland** [comment]
Those are the ones I added to the kiss path-- wasn't aware that adding kissrepo to it wasn't necessary. Thanks for the advice, will update my ~/.profile accordingly.
