### ISSUE TITLE
PCRE fails to link

### ISSUE THREAD

**Issue by davidgarland** [gkisslinux/grepo#22]
I'm unsure if this is an issue on normal KISS as well.

First, lld:

![](https://i.imgur.com/rwEg2DH.png)

then mold:

![](https://i.imgur.com/r4ZatL8.png)

binutils ld seems to just hang, consuming more and more memory.

The same segfault/hang (respectively) occurs when running `cargo install alacritty` as well, so it makes me think there's some issue with the linkers as they are on the system rather than just pcre being bad.

**Comment by git-bruh** [comment]
What version of gcc/binutils are you running ? Works fine for me with both bfd and lld

**Comment by davidgarland** [comment]
```
~ $ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc/configure --prefix=/usr --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-multilib --disable-symvers --disable-libmpx --disable-libmudflap --disable-libsanitizer --disable-werror --disable-fixed-point --disable-libstdcxx-pch --disable-nls --enable-checking=release --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-shared --enable-threads --enable-tls --enable-languages=c,c++ --without-included-gettext --with-zstd=no --with-system-zlib --build=x86_64-pc-linux-gnu --disable-bootstrap
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.0 (GCC) 
```

```
~ $ kiss list | grep gcc
gcc 11.2.0-1
```

```
~ $ kiss list | grep binutils
binutils 2.37-2
```

**Comment by git-bruh** [comment]
Hmm that seems OK, what are your CFLAGS, CXXFLAGS and LDFLAGS ?

**Comment by davidgarland** [comment]
```
~ $ echo $CFLAGS
-O2 -pipe -march=native
~ $ echo $CXXFLAGS
-O2 -pipe -march=native
~ $ echo $LDFLAGS

~ $ 
```

**Comment by git-bruh** [comment]
No clue. Could you try installing clang and then exporting CC ? `export CC=clang` then try to build these packages

**Comment by davidgarland** [comment]
Seems same thing happens. Was also careful to `export CXX=clang++`.

**Comment by git-bruh** [comment]
Could you try a fresh chroot if it doesn't bother you ? You only need a c compiler to build pcre.

**Comment by davidgarland** [comment]
Apologies for the long delay, but I got around to trying it and it works just fine in the chroot. Very odd.

I'll try updating the packages to latest in the chroot and see if that changes anything-- I didn't bother running `kiss u` yet.

**Comment by davidgarland** [comment]
Although this doesn't explain why the other linkers crash, strace gives some interesting output for `ld` when compiling `pcre`: https://gist.github.com/davidgarland/c074f8cb800e8d81750d24da21f5fe9a

the same loop of trying to open libgcc and failing happens when attempting to build gcc, annoyingly. I may try looking for a libgcc binary somewhere and giving that a try.

**Comment by davidgarland** [comment]
After comparing with the chroot, I've figured out the issue-- my machine had an extra file `libgcc.so` that `kiss owns` says does not belong to any package, and removing this fixed it entirely. This file was naturally not present in the chroot... I've no idea how it got there.
