### ISSUE TITLE
Unclean transition from OpenSSL 1.1 to 3.0

### ISSUE THREAD

**Issue by davidgarland** [gkisslinux/grepo#23]
After running `kiss u` and it updating OpenSSL, I find that now I no longer have `libssl.so.1.1`. I have no direct need for this, but the issue is that git-remote-https and curl both seem to depend upon it. If I build OpenSSL 1.1 myself and use that to rebuild git, it seems to still default to depending upon 1.1.

What is the intended way to upgrade things to the new OpenSSL 3.0 version? At the moment it's tempting to just throw an OpenSSL 1.1 package together and use that, but that does not seem like the intended path.

(Maybe this should be something I ask about upstream in kisslinux/repo instead-- if so, let me know)

**Comment by git-bruh** [comment]
Openssl 3.0 breaks ABI, hence you must do `kiss b $(kiss revdep openssl)` to rebuild all the packages that need it. It's a feature, not a bug :p 

https://kisslinux.org/tidbits#11092021

**Comment by davidgarland** [comment]
I see, thank you! I'm still not entirely sure how that's supposed to work though, as when trying to build the dependencies, curl will fail due to the lack of the old libssl.

**Comment by git-bruh** [comment]
@davidgarland You need to have the sources of all the packages downloaded first, so you can revert back to old openssl and do `kiss d $(kiss revdep openssl | sed 's|/.*||')` to download everything so that curl isnt needed again.

**Comment by davidgarland** [comment]
Alright, gotcha. Thanks again :)
