### ISSUE TITLE
[NVIDIA] Seems to get stuck after loading GRUB

### ISSUE THREAD

**Issue by NoSequel** [gkisslinux/grepo#26]
Input still works, I can login and reboot the system. Switching TTYs does not change anything, it just simply keeps saying "Loading Linux 5.15.4".

I tried several GRUB parameters, including `nomodeset`, `nouveau.nomodeset=0`, and as expected, none of them worked. All nouveau kernel options are disabled:
```
/linux-5.15.4 # cat .config | grep NOUVEAU
# CONFIG_DRM_NOUVEAU is not set
```

It seems to be working whenever I boot through my old Gentoo kernel (including my old initramfs), but whenever I boot with my new kernel it just simply does not do anything. Just vanilla kernel, no patches, and no initramfs. 

Further information:
- GPU: GM 204 (GTX 970)
- Kernel version 5.15.4
- Beforementioned gentoo kernel version: 5.10.4

Any help would be appreciated, thanks in advance!

**Comment by git-bruh** [comment]
> Input still works, I can login and reboot the system. Switching TTYs does not change anything, it just simply keeps saying "Loading Linux 5.15.4".

How is the first part possible if grub just stuck at " loading linux x.y.z" ? Did you put the kernel in the right place and on the correct partition, and does your kernel expect an initramfs?

Also this doesn't seem related to nvidia drivers since you can boot into tty without anything video-related loaded

**Comment by NoSequel** [comment]
> How is the first part possible if grub just stuck at " loading linux x.y.z"
I can navigate through the system without seeing anything, the screen stays on "Loading Linx x.y.z" but like I previously mentioned, input still works. Kernel works, and does not expect an initramfs.

**Comment by NoSequel** [comment]
> > Input still works, I can login and reboot the system. Switching TTYs does not change anything, it just simply keeps saying "Loading Linux 5.15.4".
> 
> How is the first part possible if grub just stuck at " loading linux x.y.z" ? Did you put the kernel in the right place and on the correct partition, and does your kernel expect an initramfs?
> 
> Also this doesn't seem related to nvidia drivers since you can boot into tty without anything video-related loaded

I can navigate through the system without seeing anything, the screen stays on "Loading Linx x.y.z" but like I previously mentioned, input still works. Kernel works, and does not expect an initramfs.

**Comment by git-bruh** [comment]
Hmm, I'm not able to understand what you mean when you say that input still works. How are you verifying that it works since you said you're not able to see anything? 🤔 

I think you should recheck your grub config once, or try efistub and see if it's able to load your image

**Comment by NoSequel** [comment]
> Hmm, I'm not able to understand what you mean when you say that input still works. How are you verifying that it works since you said you're not able to see anything? 🤔 
> 
> I think you should recheck your grub config once, or try efistub and see if it's able to load your image

I can simply login as root and type `reboot`, and the system reboots as it should. I can do this without seeing whatever I'm doing.

My bootloader should be fine, as like I've mentioned before, my kernel does load, my screen just gets stuck on "Loading Linux x.y.z", with no blinking cursor.

**Comment by git-bruh** [comment]
Ohh, that's weird.

> It seems to be working whenever I boot through my old Gentoo kernel (including my old initramfs), but whenever I boot with my new kernel it just simply does not do anything. Just vanilla kernel, no patches, and no initramfs.

Could you share both the .config files? The old 5.10.4  one and the new one? I'll check them tomorrow. Maybe some config option got lost in migrating to the new config.

My config is here for reference: https://github.com/git-bruh/dotfiles/blob/master/kernel

I still don't think that the nvidia drivers are related here, but they nvidia module is not loaded when you're in tty, right? Neither in the 5.10.4  nor 5.15.4

**Comment by NoSequel** [comment]
> Ohh, that's weird.
> 
> > It seems to be working whenever I boot through my old Gentoo kernel (including my old initramfs), but whenever I boot with my new kernel it just simply does not do anything. Just vanilla kernel, no patches, and no initramfs.
> 
> Could you share both the .config files? The old 5.10.4  one and the new one? I'll check them tomorrow. Maybe some config option got lost in migrating to the new config.
> 
> My config is here for reference: https://github.com/git-bruh/dotfiles/blob/master/kernel
> 
> I still don't think that the nvidia drivers are related here, but they nvidia module is not loaded when you're in tty, right? Neither in the 5.10.4  nor 5.15.4 

I didn't port over my previous configuration - I just started from the default configuration.

Here's my current .config: https://termbin.com/amey
Here's my old Gentoo .config: https://termbin.com/hbfw

I just noticed my old Gentoo config is 5.10.61 - my bad. 

And, whenever booting into my Gentoo kernel, I can see my TTY - but I don't think the NVIDIA module is loaded.

**Comment by git-bruh** [comment]
If possible could you try booting gentoo with the new kernel in which tty doesn't work? That'll confirm if it's a config issue, which you can discuss on #kisslinux irc on libera.chat
I'll check the config either way.

**Comment by git-bruh** [comment]
I think you're missing CONFIG_FB_EFI=y

**Comment by NoSequel** [comment]
> If possible could you try booting gentoo with the new kernel in which tty doesn't work? That'll confirm if it's a config issue, which you can discuss on #kisslinux irc on libera.chat
> I'll check the config either way.

I can confirm Gentoo does not work with this new kernel either. I also forgot to mention I couldn't boot this kernel with builtin nouveau drivers without NVIDIA blob either. Could there be something wrong with my framebuffer settings within my .config? I've checked several times but personally couldn't find anything wrong.

**Comment by NoSequel** [comment]
> I think you're missing CONFIG_FB_EFI=y

That indeed was the issue... Thank you so much, I'm sorry for wasting your time
