### ISSUE TITLE
[NVIDIA] kiss-xorg support?

### ISSUE THREAD

**Issue by NoSequel** [gkisslinux/grepo#27]
Is this possible? Currently, I'm running into 2 issues:

## 1
Xorg can't find the nvidia module:
https://termbin.com/hr5q

## 2
libepoxy cannot be compiled with mesa compiled using libglvnd (for some reason).

I'm not sure if I'm doing anything wrong - or if there are some modifications which need to be done for Xorg. Any help would be greatly appreciated! Thanks in advance.

**Comment by NoSequel** [comment]
I was able to compile libepoxy with libglvnd by removing `Dx11=false` from the libglvnd build file, however the Xorg error still persists.

**Comment by git-bruh** [comment]
I'll update the nvidia package in some time to install nvidia xorg libraries too, if xorg-server is installed. Then it will work.

**Comment by NoSequel** [comment]
> I'll update the nvidia package in some time to install nvidia xorg libraries too, if xorg-server is installed. Then it will work.

Alright, thanks for the response!

**Comment by git-bruh** [comment]
Hi, please update to the latest commit and rebuild the nvidia package. Then just run `nvidia-xconfig` as root and try to start xorg.

**Comment by NoSequel** [comment]
> Hi, please update to the latest commit and rebuild the nvidia package. Then just run `nvidia-xconfig` as root and try to start xorg.

Hey, it seems to be working. Thanks a lot!

**Comment by git-bruh** [comment]
Nice. Let me know if you have further issues.
