### ISSUE TITLE
Can't build nvidia package

### ISSUE THREAD

**Issue by ghost** [gkisslinux/grepo#29]
```
-> nvidia Starting build
Creating directory NVIDIA-Linux-x86_64-510.39.01-no-compat32
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 510.39.01.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
xorg-server 21.1.3-1
wayland 1.20.0-1
make[1]: *** /lib/modules/5.4.0-91-generic/build: No such file or directory.  Stop.
make: *** [Makefile:82: modules] Error 2
```

Seems to be something about kernel modules. Fresh install with kiss-xorg.

```KISS_PATH=/repo/local:/repo/grepo/bin:/repo/grepo/core:/repo/grepo/extra:/repo/grepo/nvidia:/repo/kiss-xorg/community:/repo/kiss-xorg/extra:/repo/kiss-xorg/xorg:/repo/grepo/kiss-repo/core:/repo/grepo/kiss-repo/extra:/repo/grepo/kiss-repo/testing:/repo/grepo/kiss-repo/wayland:/repo/community/community```

**Comment by git-bruh** [comment]
Hi, you should keep the kernel source tree around after building it. If you purge it then the `/lib/modules/x.y.z/build` symlink will be broken.

To fix it just `rm -rf /lib/modules/x.y.z` and do a fresh build of the kernel and do `make modules_install` as normal and then try to build the nvidia package.

**Comment by git-bruh** [comment]
Also since you're using kiss-xorg you don't need the wayland repo in KISS_PATH, and kiss-xorg repos should be places _before_ the gkiss repos so that it can override packages.

**Comment by ghost** [comment]
Actually it was I was building it in a livecd with a different kernel, but what you said led me on the right track. Thanks for the tip with the repo order too, I was trying to figure it out but guess i messed it up.
