### ISSUE TITLE
[NVIDIA] sway won't start

### ISSUE THREAD

**Issue by ghost** [gkisslinux/grepo#30]
When I run sway with `sway --unsupported-gpu` an error occurs:

```
00:00:00.000 [ERROR] [sway/main.c:62] !!! Proprietary Nvidia drivers are in use !!!
00:00:00.004 [ERROR] [wlr] [backend/backend.c:217] Found 0 GPUs, cannot create backend
00:00:00.004 [ERROR] [wlr] [backend/backend.c:386] Failed to open any DRM device
00:00:00.006 [ERROR] [sway/server.c:57] Unable to create backend
```

Can you please tell me what I missed? ALL the commands I used for install [here](https://gist.github.com/ovik41/c0aeb3b7b669ac242db8b175f9937fbf).

**Comment by git-bruh** [comment]
You shouldn't need anything more than the single modprobe in the inittab mentioned in the readme https://github.com/gkisslinux/grepo#nvidia

```
echo 'modprobe nvidia
modprobe nvidia_modeset
modprobe nvidia_uvm
modprobe nvidia_drm' > /etc/rc.d/nvidia.boot
```

This probably loads the nvidia driver without the modeset flag before `/etc/inittab` is loaded, you don't need this.

If it still doesn't work after removing `/etc/rc.d/nvidia.boot` then post a `dmesg` log along with `strace sway --unsupported-gpu > log 2>&1` and the output of `log`.

**Comment by ghost** [comment]
Yes, that didn't work, now another error appears:
[strace](https://termbin.com/p6dp), [dmesg](https://termbin.com/9pwv)

**Comment by git-bruh** [comment]
```
openat(AT_FDCWD, "/dev/dri/renderD128", O_RDWR|O_CLOEXEC) = -1 EACCES (Permission denied)
```

There is still a permission issue. Ssnd the output of `ls -l /dev/dri`

You probably just forgot to enable mdev which handles permission changes so just `kiss b libudev-zero` and `ln -s /etc/sv/mdev /var/service` and reboot

**Comment by ghost** [comment]
Thank you so much, that was the problem!
