### ISSUE TITLE
Open source NVIDIA drivers

### ISSUE THREAD

**Issue by ghost** [gkisslinux/grepo#31]
It would be nice to update the repository and add the nvidia-open package 😃
(sway with native wlroots works for me without artifacts)

**Comment by git-bruh** [comment]
The open source kernel drivers only support GPUs from the 3xxx series onwards and I only have a 1660, so I won't be able to test it.

**Comment by git-bruh** [comment]
Nvm, it does support 16xx and 20xx series aswell. Fixed and added an option to use proprietary module

**Comment by ghost** [comment]
Got it, thanks. Let's hope for better support for the open source driver.
