### ISSUE TITLE
libglvnd: 1.4.0

### ISSUE THREAD

**Issue by ghost** [gkisslinux/grepo#32]
https://gitlab.freedesktop.org/glvnd/libglvnd/-/archive/v1.4.0/libglvnd-v1.4.0.tar.gz
And if I may ask - why sway version is upstream and not 1.7?

**Comment by git-bruh** [comment]
Sway was using the latest git commit beacuse I thought it might fix some issues with nvidia cards, I think 1.7 would work fine too.
