### ISSUE TITLE
tmp folder does not have rw permissions set

### ISSUE THREAD

**Issue by josephreynolds1** [gkisslinux/grepo#4]
tmp folder does not have correct rw permissions set for all users
currently only root user can write to the tmp folder.

permissions need to be :

**chmod 1777 /tmp**

drwxrwxrwt 21 root root 12288 Apr 28 16:18 /tmp

**Comment by rachelambda** [comment]
This is odd, the baselayout build installs with permissions 1777, but the folder still has permissions set to 0777. I've changed it manually though and this should not be an issue with future releases, thanks for the help!

**Comment by sincetheflood** [comment]
The latest release (0.4.0) still has issues with rw, /tmp's permissions are set to 1755 instead 1777. In case it makes a difference, I'm using Arch as the host OS, btrfs as the guest filesystem, and `tar vxf gkiss-chroot.tar.xz -C /mnt` as the tar command.

**Comment by rachelambda** [comment]
I updated the tarball, thanks for notifying me!
