### ISSUE TITLE
ERROR kiss Checksum mismatch

### ISSUE THREAD

**Issue by xeaal** [gkisslinux/grepo#53]
Trying to install GKISS Linux, getting this error when trying to rebuild all packages

**Comment by xeaal** [comment]
![2024-01-29-220030_723x96_scrot](https://github.com/kiss-community/grepo/assets/36858499/e52f8389-1123-43db-8ff7-7d82c8874c2d)
sorry it's not in a text form, can't copy out of terminal

**Comment by git-bruh** [comment]
Pushed a fix

**Comment by xeaal** [comment]
oh so it was you? i thought i fixed it somehow with `kiss c kiss`. thanks

**Comment by git-bruh** [comment]
`kiss c` would fix it as well, it was just a matter of updating the checksums
