### ISSUE TITLE
about symlinks

### ISSUE THREAD

**Issue by dylanaraps** [gkisslinux/grepo#9]
What I meant by symlinks files is the following: https://github.com/jedavies-dev/kiss-aarch64/tree/master/repo/musl

Only the unchanged files are symbolically linked. jedavies-dev would update their symlinks to point to .`./../repo/...` for example. There's no need to symlink each package in other words. The user can keep the official repositories wherever they like as you include the submodule *only for the packages you have partially modified*.

Does this make sense? It saves you symlinking *everything*.

**Comment by dylanaraps** [comment]
Will close this as it's not a bug but a query. Just wanted to send the message.  You're free to do this however you like. :+1:

**Comment by rachelambda** [comment]
yeah I know, this just tidies up things a bit as the user doesn't need to have two seperate user repositories. I was also gonna fix links to versions, checksums etc for other packages but I've been taking it a bit slow lately.
